log_info("akhenaten: load buildings started")

import building.config
import building.prototype
import building.building_params
import building.bazaar
import building.wharf_common
import building.dock
import building.transport_wharf
import building.warship_wharf
import building.fishing_wharf
import building.shipyard
import building.ferry
import building.roadblock
import building.house
import building.monument
import building.mastaba
import building.sphinx
import building.obelisk
import building.sun_temple
import building.abu_simbel
import building.caesareum
import building.alexandria_library
import building.mausoleum
import building.pharos_lighthouse
import building.royal_tomb
import building.pyramid
import building.farm
import building.fort
import building.education
import building.academy
import building.apothecary
import building.scribal_school
import building.palace
import building.temple
import building.shrine_osiris
import building.shrine_ra
import building.shrine_ptah
import building.shrine_seth
import building.shrine_bast
import building.statue
import building.statue_small
import building.statue_medium
import building.statue_large
import building.mansion
import building.workshop
import building.bricks_workshop
import building.lamp_workshop
import building.paint_workshop
import building.chariots_workshop
import building.cattle_ranch
import building.clay_pit
import building.wood_cutter
import building.temple_complex
import building.entertainment
import building.booth
import building.festival_square
import building.firehouse
import building.police_station
import building.hunting_lodge
import building.pottery
import building.papyrus_maker
import building.weaver
import building.weaponsmith
import building.mine_copper
import building.mine_gold
import building.mine_gems
import building.granary
import building.storage_yard
import building.health
import building.mortuary
import building.architect_post
import building.courthouse
import building.garden
import building.work_camp
import building.road
import building.irrigation_ditch
import building.bridge
import building.dike
import building.food_mill
import building.industry_office
import building.well
import building.water_lift
import building.water_supply
import building.gatehouse_common
import building.brick_gatehouse
import building.mud_gatehouse
import building.decorative_gatehouse
import building.tower_gatehouse
import building.zoo
import building.conservatory
