log_info("akhenaten: load buildings started")

import building.config
import building.prototype
import building.building_params
import building.bazaar
import building.dock
import building.wharf_common
import building.transport_wharf
import building.warship_wharf
import building.fishing_wharf
import building.shipyard
import building.roadblock
import building.house
import building.monument
import building.mastaba
import building.pyramid
import building.farm
import building.fort
import building.education
import building.palace
import building.temple
import building.shrine
import building.statue
import building.statue_small
import building.statue_medium
import building.statue_large
import building.mansion
import building.workshop
import building.temple_complex
import building.entertainment
import building.booth
import building.firehouse
import building.hunting_lodge
import building.pottery
import building.papyrus_maker
import building.weaponsmith
import building.mine_copper
import building.mine_gold
import building.mine_gems
import building.granary
import building.health
import building.architect_post
import building.courthouse
import building.work_camp
import building.road
import building.well
import building.water_supply