log_info("akhenaten: city econmoic started")

default_prices = [
    {res: RESOURCE_NONE, buy: 0, sell: 0},
    {res: RESOURCE_GRAIN, buy: 28, sell: 21},
    {res: RESOURCE_MEAT, buy: 47, sell: 35},
    {res: RESOURCE_LETTUCE, buy: 33, sell: 25},
    {res: RESOURCE_CHICKPEAS, buy: 33, sell: 25},
    {res: RESOURCE_POMEGRANATES, buy: 33, sell: 25},
    {res: RESOURCE_FIGS, buy: 33, sell: 25},
    {res: RESOURCE_FISH, buy: 42, sell: 33},
    {res: RESOURCE_GAMEMEAT, buy: 44, sell: 34},
    {res: RESOURCE_STRAW, buy: 21, sell: 16},
    {res: RESOURCE_WEAPONS, buy: 325, sell: 275},
    {res: RESOURCE_CLAY, buy: 38, sell: 29},
    {res: RESOURCE_BRICKS, buy: 150, sell: 120},
    {res: RESOURCE_POTTERY, buy: 140, sell: 105},
    {res: RESOURCE_BARLEY, buy: 48, sell: 37},
    {res: RESOURCE_BEER, buy: 185, sell: 140},
    {res: RESOURCE_FLAX, buy: 54, sell: 42},
    {res: RESOURCE_LINEN, buy: 210, sell: 160},
    {res: RESOURCE_GEMS, buy: 120, sell: 92},
    {res: RESOURCE_LUXURY_GOODS, buy: 310, sell: 150},
    {res: RESOURCE_TIMBER, buy: 225, sell: 170}, 
    {res: RESOURCE_GOLD, buy: 0, sell:  0},     
    {res: RESOURCE_REEDS, buy: 31, sell: 23},
    {res: RESOURCE_PAPYRUS, buy: 200, sell: 165},
    {res: RESOURCE_STONE, buy: 38, sell: 29},
    {res: RESOURCE_LIMESTONE, buy: 46, sell: 35},
    {res: RESOURCE_GRANITE, buy: 60, sell: 45},
    {res: RESOURCE_UNUSED12, buy: 0,sell:  0},
    {res: RESOURCE_CHARIOTS, buy: 375, sell: 315},
    {res: RESOURCE_COPPER, buy: 240, sell: 185},
    {res: RESOURCE_SANDSTONE, buy: 40, sell: 32},
    {res: RESOURCE_OIL, buy: 110, sell: 85},
    {res: RESOURCE_HENNA, buy: 40, sell: 30},
    {res: RESOURCE_PAINT, buy: 155, sell: 116},
    {res: RESOURCE_LAMPS, buy: 250, sell: 190},
    {res: RESOURCE_MARBLE, buy: 72, sell: 54},
]