log_info("akhenaten: eventmsg auto phrases started")

male_name_prefixes = [
  "Ak", "Be", "Ge", "He", "Iy", "Kh", "Me", "Mi", "Na", "Nd", "Nl", "Ni", "Os", "Pa", "Pt", "Se", "Ta", "We", 
  "Ya", "Za", "Fe", "Ab", "Ba", "Du", "En", "He", "He", "Ir", "Is", "Kl", "Ki", "Me", "Mu", "Ne", "No", "Pe", 
  "Re", "Su", "Te", "Ub", "Wr", "Pr", "Sa", "At", "Bt", "Gr", "He", "In", "Kz", "Me", "Mi", "Nq", "Nu", "Np"
]

male_name_middles = [
  "uno", "nermer", "nuba", "ma", "ar", "enstho", "ntuemh", "nnak", "bhot", "ferme", "s", "ml", "ork", "she", 
  "ahsheps", "nnedj", "hr", "pawetmo", "nha", "zamou", "nam", "a", "ktwer", "ath", "e", "rnei", "tepheneb", 
  "etemkh", "ama", "retseg", "tnodjm", "feru", "ferti", "sh", "ddjed", "tail", "tishe", "ast", "pwaw",
]

male_name_postfixes = [
  "sh", "ut", "th", "ka", "us", "th", "at", "ht", "ep", "nu", "hi", "ot", "on", "du", "es", "em", "qa", 
  "se", "mu", "kh", "es", "na", "el", "or", "hy", "th", "ti", "as", "eb", "at", "ya", "er", "et", "ra", 
  "ri", "et", "et", "ja", "ri", "et", "et", "ro", "ru", "pu", "po", "ee", "aa", "yt", "or", "ot", "da"
]

female_name_postfixes = [
  "et", "t", "is", "it", "a", "ia", "ris", "tis", "mes", "nefret", "hotep", "ankh", "nofer", 
  "tet", "sat", "mut", "ka", "ra", "en", "nefer", "sheps", "em", "heb", "ib", "maat", 
  "nut", "pet", "merit", "bast", "isis", "hathor", "senet", "neit", "tefnut", "iat", 
  "weret", "ren", "hesy", "khnumet", "setep", "shepset", "iry", "nofret", "khet", "wadj",
  "tjau", "ites", "ia", "wati", "neb", "mery", "seneb", "nedjem", "heru", "amun", "ptah"
]

figure_name_generator {
  prefixes: male_name_prefixes
  middles: male_name_middles
  male_postfixes: male_name_postfixes
  female_postfixes: female_name_postfixes
}

default_citizen_male_names = [
  "Sutymose",
  "Nimlot",
  "Pamu",
  "Shabaka",
  "Zazamoukh",
  "Wahka",
  "Osorkon",
  "Jarha",
  "Genubath",
  "Bakenmut",
  "Wepwawetmose",
  "Wahankh",
  "Ankhnefer",
  "Horwebbefer",
  "Horapollo",
  "Kaka",
  "Khensthoth",
  "Kha'y",
  "Inarus",
  "Herenamenpenaef",
  "Narmer",
  "Nebitka",
  "Nebmaatre",
  "Naga-ed-der",
  "Menmire",
  "Amenmose",
  "Addaya",
  "Ankhsheshonq",
  "Benermerut",
  "Djedptahefankh",
  "Akunosh",
  "Amenhirkopshef",
  "Ameneheb",
  "Apophis",
  "Bakenkhonsu",
  "Deniuenkhons",
  "Heqamaatre",
  "Horemheb",
  "Hornedjitef",
  "Hosay",
  "Harkhuf",
  "Harmhabi",
  "Ibana",
  "Irhoreru",
  "Ishpi",
  "Iufankh",
  "Iufenamun",
  "Iuseneb",
  "Kadjadja",
  "Khonsirdais",
  "Khakheperraseneb",
  "Manetho",
  "Menmet-Ra",
  "Merirahasetef",
  "Mernebptah",
  "Meryrahashtef",
  "Neferhotep",
  "Neshorpakhered",
  "Miankkhnum",
  "Niumateped",
  "Pedibastet",
  "Qenymin",
  "Rudiju",
  "Sneferu",
  "Heptseshet",
  "Amkhaibitu",
  "Maatafemsesh",
  "Setqesu",
  "Taret",
  "Hetchabehu",
  "Amsenef",
  "Ambesek",
  "Thenemi",
  "Sethgregorshef",
  "Hansptah",
  "Ankhenrimhat",
  "Nenedjasondjed",
  "Jeremshepenwet",
  "Sasolomonmut",
  "Rajohnhotep",
  "Kethnakte",
  "Akenaba",
  "Shmikenakht",
  "Roneith",
  "Ankhscotshonq",
  "Amenwaynsu",
  "Tanutamun",
  "Wadjtonymose",
  "Labarjamoukh",
  "Saltsenkhamen",
  "Zizzamoukh",
  "Pramessu",
  "Sipair",
  "Shawnbaka",
  "Sisekhmet",
  "Panas",
  "Maakha",
  "Butehamun",
  "Nekhen",
  "Ankhu",
  "Craigamun",
  "Remensses",
  "Ashaamedes",
  "Ib'remedes",
  "Bewethaat",
  "Inyotef",
  "Niankhkhnum",
  "Khnumhotep",
  "Sinuhe",
  "Senwosret",
  "Setka",
  "Niumateped",
  "Ahkenrusses",
  "Padalineith",
  "Montuhotep",
  "Keraghotep",
  "Montumery",
  "Horemchadhotep",
  "Meryrahashtef",
  "Ipy",
  "Akunosh",
  "Akencheres",
  "Djedptahefankh",
  "Herenamenpenaef",
  "Simontu",
  "Mekuniwetel",
  "Nespanetjerenpere",
  "Shedsunefertum",
]

default_pharaoh_male_names = [
  "Tutu",
  "Shewet",
  "Bebaat",
  "Neferheret",
  "Naasheba",
  "Nebabui",
  "Webaoner",
  "Ramesses",
  "Hemjunu",
  "Ptahhotep",
  "Imhotep",
  "Prehotep",
  "Amasis",
  "Ptahnefer",
  "Impeihotep",
  "Menkaure",
  "Gebu",
  "Ankh-hori",
  "Khonshotep",
  "Khonsnefru",
  "Merykhons",
  "Beshotep",
  "Merybes",
  "Ptahhudjankhef",
  "Meryedjo",
  "Edjohotep",
  "Heqetmeses",
  "Menheqet",
  "Akenheqet",
  "Kheprihotep",
  "Akenkhepri",
  "Merykhepri",
]

default_tax_collector_names = [
  "Itchenkhamen",
  "Techemes",
  "Djesersukhons",
  "Ay",
  "Aadmeru",
  "Nebumery",
  "Nebaak",
  "Burglakhamen",
  "Amunloot",
  "Pedibandit",
  "Nebnodjmet",
  "Ankhefeneb",
  "Akeneb",
  "Nebtet",
  "Nekhbehotep",
  "Herishef",
]

default_engineer_names = [
  "Nebwam",
  "Ankhmery",
  "Pasebakhaenniut",
  "Her-uben",
  "Seshed",
  "Kingmery",
  "Pedidavi",
  "Akenturner",
  "Carnegmose",
  "Forbesankh",
  "Snotmose",
  "Rockesenmut",
  "Anhetepf",
  "Seshemfenti",
  "Minkhat",
  "Nehahra",
  "Ankhwa",
  "Yuya",
  "Kaha",
  "Poy",
  "Fraankptah",
  "Stevemeses",
  "Merymar",
  "Tjanefer",
  "Takany",
  "Wadjet",
  "Paser",
  "Hetchabehu",
  "Hrafhaf",
  "Nehahra",
  "Nehawelti",
  "Neret",
]

default_fireman_names = [
  "Onurishotep",
  "Meryonuris",
  "Onurisnodjmet",
  "Karem",
  "Iuseneb",
  "Khahor",
  "Wahmery",
  "Ankhmery",
  "Techemesmery",
  "Nestanebetasheru",
  "Raia",
  "Shedsunefertum",
  "Serapion",
  "Tymisba",
  "Taharqa",
  "Panehsy",
  "Apoutit",
  "Amanishakheto",
  "Abana",
  "Bunefer",
  "Hatshepsut",
  "Hettimenhu",
  "Iras",
  "Khamereernebty",
  "Kiya",
  "Mehetweshket",
  "Kristenefer",
  "Nefertiti",
  "Neferkatia",
  "Shananofru",
  "Awildamer",
  "Andremose",
  "Hetemaria",
  "Heidinefer",
  "Lisatiti",
  "Duatnefret",
  "Nyla",
  "Donamoses",
  "Claudipatra",
  "Tabubu",
  "Tetisheri",
  "Yunet",
  "Weretimtes",
  "Pebatma",
  "Sofiwepet",
  "Neferneferuaten",
  "Ubastet",
  "Baktwerel",
]

default_juggler_names = [
  "Marakhen",
  "Seshedakhen",
  "Nebuakhen",
  "Hedjakhen",
  "Siamun",
  "Nodjmet",
  "Amenemopet",
  "Mekuniwetel",
  "Meryptah",
  "Naneferkeptah",
  "Neshi",
  "Padiamenet",
  "Shepenwepet",
  "Udjahorresne",
  "Wenis",
  "Payneferher",
]

default_musician_names = [
  "Searseneb",
  "Akenwalmart",
  "Bakenbradleehotep",
  "Nefermacy",
  "Pennybastet",
  "Gapahmose",
  "Amunherpanesha",
  "Huya",
  "Nigmed",
  "Paperpa",
  "Tefibi",
  "Amihotep",
  "Kevinefer",
  "Tobykhamen",
  "Pebes",
  "Salatis",
]

default_dancer_names = [
  "Hapimen",
  "Tielamun",
  "Nebrianmes",
  "Harsiese",
  "Bay",
  "Bek",
  "Serkheru",
  "Dannikhamen",
  "Meryhem",
  "Pethotep",
  "Wenefakhen",
  "Shetchaat",
  "Heredhotep",
  "Ahinodjmet",
  "Ahitut",
  "Nodjmet-ta-sherit",
  "Pepi",
  "Thothotep",
  "Smendes",
  "Sithoth",
  "Minmery",
  "Siunnefer",
  "Unneferhotep",
  "Minhotep",
  "Merythoth",
  "Djau",
  "Bakenaten",
  "Ishpi",
  "Katep",
  "Pathemwia",
  "Nigmed",
  "Suty",
]

default_senet_player_names = [
  "Yoyomaatre",
  "Bakenabbamaat",
  "Claudipaatra",
  "Wia",
  "Wabkhet",
  "Heret",
  "Naunakht",
  "Heria",
  "Hunro",
  "Haphen-refer",
  "Retep",
  "Hatshepsut",
  "Nofertiri",
  "Ptennisnet",
  "Ankhesenaten",
  "Apoutit",
  "Beketaten",
  "Dedi",
  "Duathor",
  "Esemkhebe ",
  "Hathor",
  "Hehenhit",
  "Henutnofret",
  "Hetepheres",
  "Iniihue",
  "Ipip",
  "Isetnofret",
  "Iutenheb",
  "Karem",
  "Khamaat ",
  "Kiya",
  "Meketre" ,
]

default_osiris_priest_names = [
  "Siosiris",
  "Osirishotep",
  "Pedosiris",
  "Akenosiris",
  "Wahosiris",
  "Tutankhosiris",
  "Merenosiris",
  "Iufosiris",
  "Sebekhotep",
  "Sisebek",
  "Wasebek",
  "Akensebek",
  "Pedimin",
  "Tutankhmin",
  "Merymin",
  "Akenmin",
]

default_ra_priest_names = [
  "Menma'atra",
  "Akenra",
  "Nefera",
  "Ranofret",
  "Mutnodra",
  "Meryra",
  "Ramose",
  "Rashepses",
  "Ma'athotep",
  "Meryma'at",
  "Pedima'at",
  "Neferma'at",
  "Akenhorus",
  "Iunhorus",
  "Bakenhorus",
  "Wahorus" ,
]

default_ptah_priest_names = [
  "Ptahhotep",
  "Ptahhudjankef",
  "Ptahmose",
  "Pediptah",
  "Ptahhemhat-Ty",
  "Ptahhemakehet",
  "Akenptah",
  "Waptah",
  "Amonhotep",
  "Akenamon",
  "Siamon",
  "Bakenamon",
  "Merythoth",
  "Thothnodjmet",
  "Akenthoth",
  "Pedithoth",
]

default_seth_priest_names = [
  "Siseth",
  "Wahseth",
  "Sethmesses",
  "Meryseth",
  "Sethmose",
  "Pediseth",
  "Akenseth",
  "Sethnodjmet",
  "Anubishotep",
  "Anubismose",
  "Bakenanubis",
  "Sianubis",
  "Akensekhmet",
  "Sekhmetnakht",
  "Niankhsekhmet",
  "Merysekhmet",
]

default_bast_priest_names = [
  "Pedibast",
  "Sitbast",
  "Basthotep",
  "Bastnofret",
  "Bastmire",
  "Bastwedjebu",
  "Bastemshaf",
  "Akenbast",
  "Isetnofret",
  "Sitisis",
  "Isismose",
  "Isisnodjmet",
  "Sithathor",
  "Pedihathor",
  "Meryhathor",
  "Hathornofret",
]

default_senet_player_names = [
  "Mercia",
  "Bunefer",
  "Ipuky",
  "Innovandora",
  "Sinuhe",
  "Nebefer",
  "Nenufer",
  "Neskhons",
  "Pekersater",
  "Reddjedet",
  "Seshseshet",
  "Tabubu",
  "Taweret",
  "Tefenet",
  "Ubastet",
  "Wenis" ,
]

default_trade_caravan_names = [
  "Osiris' Blessing",
  "Ra's Fortune",
  "Ptah Smiles",
  "Bast's Glory",
  "Seth's Mover",
  "Chickpea",
  "Pomengranate",
  "Ahmery's Fig",
  "Sunset",
  "Nile Cruiser",
  "Big Floater",
  "Anqet",
  "Khnenmu",
  "Luck of Hapi",
  "Conveyor",
  "Transporter",
]

default_trader_ship_names = [
  "Nile Master",
  "Pride of Osiris",
  "Tefnut Cruiser",
  "Purveyor",
  "Swift Trader",
  "Breeze",
  "Barterer",
  "New Dealer",
  "Swapper",
  "Barge of Plenty",
  "Pomegranate",
  "Navigator",
  "Bounty of Ptah",
  "Procurer",
  "Demander",
  "Supplier",
]

default_noble_names = [
  "Nebnefer",
  "Anhirkawi",
  "Kenhirkhopeshef",
  "Anupemheb",
  "Prahotep",
  "Panhesi",
  "Paneb",
  "Sithoth",
  "Kjaemwase",
  "Neferabu",
  "Amennakht",
  "Kha'nun",
  "Mentmose",
  "Patwere",
  "Pa'anuket",
  "Harshire",
  "Keneben",
  "Hormin",
  "Tjanefer",
  "Amenwa",
  "Pentaweret",
  "Pentahetnakht",
  "Nesamenopet",
  "Sobeksankh",
  "Pinejem",
  "Sinnejem",
  "Ankhu",
  "Ametju",
  "Rensi",
  "Khunanpu",
  "Thutinakhte",
  "Khentika",
]

default_market_trader_names = [
  "Ptahshedu",
  "Ankhtifi",
  "Beshirkopshef",
  "Merybes",
  "Bakenbes",
  "Heqethotep",
  "Waheqet",
  "Nefertumhotep",
  "Merynefertum",
  "Nephthysankh",
  "Meryneith",
  "Siselkis",
  "Merytaweret",
  "Medesian",
  "Akenimsety",
  "Akenselket",
  "Si'isis",
  "Akenisis",
  "Akenfluoris",
  "Novakhamen",
  "Merytecheknen",
  "Mektyabehu",
  "Khenmrshabehu",
  "Hetch-abehu",
  "Mesedjerikem",
  "Saieb",
  "Sarekhyt",
  "Wahetau",
  "Eckerdhotep",
  "Meryrevco",
  "Bakenosco",
  "Akenbayer",
]

default_scribes_names = [
  "Tesersukhons",
  "Anubisherkhepshef",
  "Anubismose",
  "Naneferkeneith",
  "Sekerhotep",
  "Merygeb",
  "Noferanpu",
  "Anpunodjmet",
  "Tutankhanpu",
  "Meryhaat",
  "Swaadjhaat",
  "Feqaadjem",
  "Awsenef",
  "Nebseshta",
  "Benumery",
  "Duamutefhotep",
]

default_herbalist_names = [
  "Abemose",
  "Meryneba",
  "Fenti",
  "Heptsesh",
  "Uath-nesert",
  "Wahnet",
  "Netti",
  "Techemes",
  "Bebaat",
  "Webed",
  "Kymery",
  "Nenesert",
  "Shemshu",
  "Hepertmenu",
  "Selkishotep",
  "Pedijon" ,
]

default_water_carrier_names = [
  "Casijonesahken",
  "Ptahshepses",
  "Pinotmou",
  "Necho",
  "Dougeptah",
  "Ptahnetjeru",
  "Sabef",
  "Salatis",
  "Pamose",
  "Siptah",
  "Hori",
  "Montuhirkopshef",
  "Fiskhamen",
  "Khufu",
  "Thutmose",
  "Nesmont" ,
]

default_worker_names = [
  "Merydonut",
  "Samspadehotep",
  "Mektuankh",
  "Kojahken-ta-sherit",
  "Bluhotep",
  "Ahkenbadgaten",
  "Cuffnefer",
  "Pedibarnahmose",
  "Rasiren",
  "Magnumhotep",
  "Rockfordmaatre",
  "Kojahken",
  "Fridayahmose",
  "Polyseneb",
  "Wiggumwenemef",
  "Hammereperre" ,
]

default_teacher_names = [
  "Takelot",
  "Amineweh",
  "Nebuwaat",
  "Bewet",
  "Iaret",
  "Neret",
  "Ankhet",
  "Hedjemet",
  "Khenmeshemefkaat",
  "Mekeshkesh",
  "Amhetepf",
  "Avaris",
  "Raneb",
  "Rahotep",
  "Petety",
  "Bitakhen" ,
]

default_librarian_names = [
  "Amoy",
  "Mose",
  "Mektu",
  "Wamektu",
  "Wahikem",
  "Tutwa",
  "Tjepu",
  "Peksater",
  "Peftjauabastet",
  "Ma'athotep",
  "Pramessu",
  "Roma-Roy",
  "Sethe",
  "Senebtyfy",
  "Yanhamu",
  "Teti-en" ,
]

default_embalmer_names = [
  "Menmaatre",
  "Clarkenophis",
  "Ankhomallhotep",
  "Horoconnhotep",
  "Benjaseneb",
  "Khaemaleksnefer",
  "Merenadamptah",
  "Adamwenemef",
  "Bobenkhonsu",
  "Billamun",
  "Merydanseneb",
  "Pashacrisedu",
  "Wendjedarrindjed",
  "Damiankhef",
  "Nebrethotep",
  "Shependenniswepet",
  "Nesedtefnut",
  "Hericihor",
  "Gabubath",
  "Khemi",
  "Anaf",
  "Usekhnemtet",
  "Iryaahotep",
  "Aadset",
  "Medesmektu",
  "Shemshutchesm",
  "Munef",
  "Medjed",
  "Ipwetuhaat",
  "Ahkenptah",
  "Inbahken",
  "Hemethotep",
]

default_market_boy_names = [
  "Keret",
  "Aqhat",
  "Shachar",
  "Shalim",
  "Yam",
  "Kothar",
  "Khasis",
  "Khirkhib",
  "Mot",
  "Resheph",
  "Yassib",
  "Hirgab",
  "Radmanu",
  "Athtar",
  "Yatpah",
  "Yarikh" ,
]

default_physician_names = [
  "Psuro",
  "Psaro",
  "Karoya",
  "Kasaya",
  "Shekitku",
  "Hetauiah",
  "Hysbroze",
  "Uyek",
  "Skarabya",
  "Dogon",
  "Kubafang",
  "Medjay",
  "Askut",
  "Tjury",
  "Kumi",
  "D'lekta" ,
]

default_soldier_archer_names = [
  "Abdullah",
  "Sahoser",
  "Muammar",
  "Fez",
  "Garamantes",
  "Ayoub",
  "Jamil",
  "Raafat",
  "Salheen",
  "Muskat",
  "Hishaam",
  "Ataar",
  "Faywi",
  "Khalid",
  "Wafiti",
  "Hajjaji",
]

default_enemy_egyptian_names = [
  "Sebiumeker",
  "Arensuphis",
  "Kasnta",
  "Alara",
  "Piye",
  "Shabako",
  "Taharqa",
  "Apedernak",
  "Aqrakamani",
  "Natakamani",
  "Khal",
  "Grrski",
  "Sobek",
  "Kashta",
  "Shebitku",
  "Tanwetamani",
]

default_enemy_assyrian_names = [
  "Qar",
  "Salitis",
  "Apop",
  "Ammi-enshi",
  "Bnon",
  "Apachnan",
  "Seshi",
  "Khamudi",
  "Khian",
  "Iannas",
  "Assis",
  "Aamu",
  "Yakbam",
  "Jacob-Her",
  "Sekhanre",
  "Yoam",
]

default_enemy_hittite_names = [
    "Pithana",
    "Labarna",
    "Hattusili",
    "Mursili",
    "Hantili",
    "Zidanta",
    "Amnuna",
    "Telipinu",
    "Huzziya",
    "Alluwamna",
    "Muwatalli",
    "Arnuwanda",
    "Tudhaliya",
    "Suppiluliuma",
    "Karunta",
    "Anitta",
]

default_enemy_roman_names = [
    "Goliath",
    "Beelzebub",
    "Abimelech",
    "Phicol",
    "Achish",
    "Ahaziah",
    "Minos",
    "Dagon",
    "Potidas",
    "Alcinous",
    "Asterius",
    "Nia",
    "Phaestos",
    "Dedalus",
    "Icarus",
    "Britomantis",
]

default_enemy_seapeople_names = [
    "Tushratta",
    "Artatama",
    "Tarmitessup",
    "Saushtatar",
    "Sulpae",
    "Zabazuna",
    "Zuja",
    "Pasatatar",
    "Kirta",
    "Idrimi",
    "Niqmepa",
    "Samas",
    "Kipteshub",
    "Ilimilimma",
    "Sataura",
    "Huradi",
]

default_enemy_ship_names = [
    "Destructor",
    "Squasher",
    "Demolisher",
    "Mangler",
    "Obliterater",
    "Slasher",
    "Mutilator",
    "Challenger",
    "Avenger",
    "Ruiner",
    "Claw",
    "Talon",
    "Charger",
    "Spoiler",
    "Wrecker",
    "Plunderer",
]

default_enemy_batalion_names = [
    "Putasokinhet",
    "Xander",
    "Ironrod",
    "Hat-tubig",
    "Reckless Rodent",
    "Ancient One",
    "Bedu",
    "Trespasser",
    "Nomad",
    "Wanderer",
    "Sandman",
    "Conan",
    "Shabbaba",
    "Rababa",
    "Fuqara",
    "Petra" ,
]

default_enemy_hittite_names = [
    "Shumash",
    "Shalmaneser",
    "Tikulti",
    "Esnacher",
    "Urtaku",
    "Nabopollassar",
    "Ashur",
    "Bel-ibni",
    "Sennacher",
    "Ashurnadin",
    "Alkhut",
    "Neskhut",
    "Tilkhut",
    "Belnikut",
    "Belnesir",
    "Shasazur",
]

default_roman_batalion_names = [
    "Marcus",
    "Arminius",
    "Lucullus",
    "Crassus",
    "Gregorius",
    "Lucius",
    "Gnaeus",
    "Antonius",
    "Septimus",
    "Berosus",
    "Cornelius",
    "Lycus",
    "Alexus",
    "Lascivius",
    "Gaius",
    "Garrulus",
]

default_persian_batalion_names = [
    "Orodes",
    "Pakores",
    "Shurtruk",
    "Arsames",
    "Bagoas",
    "Artabanus",
    "Cyaxares",
    "Astyages",
    "Teispes",
    "Haxamanish",
    "Shulla",
    "Hystaspes",
    "Bardiya",
    "Smerdis",
    "Artaxerxes",
    "Nahhunte" ,
]

default_seapeople_batalion_names = [
    "Salmani",
    "Mirjama",
    "Tesmet",
    "Al Busir",
    "Ishtar",
    "Ahkmed",
    "Al Khaban",
    "Al Mustaf",
    "Hassan",
    "Samtiyar",
    "Tekdinar",
    "Santimer",
    "Almut",
    "Yusif",
    "Tandinar",
    "Tesmar",
]

figure_names = [
  { type:FIGURE_TAX_COLLECTOR  },

  // Example: Generated names from three parts (prefix + middle + postfix)
  // { type:FIGURE_CITIZEN, use_parts_generation:true, prefixes:male_name_prefixes, middles:male_name_middles, postfixes:male_name_postfixes },
  
  // Or use predefined names list:
  // { type:FIGURE_CITIZEN, names:default_citizen_male_names },

  // empty names
  { type:FIGURE_EXPLOSION, empty_name:true  },
  { type:FIGURE_STANDARD_BEARER, empty_name:true  },
  { type:FIGURE_FISHING_POINT, empty_name:true  },
  { type:FIGURE_FISHING_SPOT, empty_name:true  },
  { type:FIGURE_CREATURE, empty_name:true  },
  { type:FIGURE_CHARIOR_RACER, empty_name:true  },
]