log_info("akhenaten: load modules started")

include(":akhenaten.conf")
include(":hotkeys.conf")

import math
import ui_common
import ui_main_menu
import rating_points
import common
import images
import city_sounds
import walker_sounds
import ui_window_features
import buildings
import overlays
import building_sounds
import images
import ui_advisor_labor
import ui_advisor_military
import ui_advisor_ratings
import ui_labor_priority_window
import images_remap
import ui_overlay_menu
import imagepaks
import missions
import mission_5_timna
import mission_6_behdet
import mission_8_selima
import mission_9_abu
import figures
import ui_hold_festival_window
import localization
import localization_en
import ui_advisor_entertainment
import ui_advisor_population
import building_menu
import desirability
import ui_send_gift_window
import kingdome_relation
import ui_advisor_trade
import floodplain
import ui_advisors_window
import ui_terrain_info
import ui
import ui_figure_trader_window
import ui_figure_enemy_window
import ui_top_menu_widget
import ui_advisor_religion
import ui_advisor_finance
import ui_advisor_health
import houses
import fonts
import routing
import ui_bazaar_window
import ui_advisor_chief
import ui_mission_briefing_window
import economic
import migration
import ui_empire_window
import ui_advisor_education
import ui_advisor_imperial
import ui_workshop_window
import ui_sidebar_window
import ui_batalion_window
import music
import invasions
import enemies
