log_info("akhenaten: ui config started")

import ui_common
import ui_main_menu
import ui_advisors_window
import ui_terrain_info
import ui_figure_info
import ui_hold_festival_window
import ui_advisor_entertainment
import ui_advisor_population
import ui_send_gift_window
import ui_advisor_trade
import ui_figure_trader_window
import ui_figure_enemy_window
import ui_top_menu_widget
import ui_advisor_religion
import ui_advisor_finance
import ui_advisor_health
import ui_granary_info
import ui_records_window
import ui_bazaar_window
import ui_advisor_chief
import ui_mission_briefing_window
import ui_empire_window
import ui_advisor_education
import ui_advisor_imperial
import ui_workshop_window
import ui_sidebar_window
import ui_batalion_window
import ui_mods_window
import ui_messages_window
import ui_house_window
import ui_advisor_labor
import ui_advisor_military
import ui_advisor_ratings
import ui_labor_priority_window
import ui_window_features
import ui_overlay_menu
import ui_market_buyer_window
import ui_widgets
import ui_message_dialog
import ui_display_options_window


