log_info("akhenaten: walker sounds started")

walker_sounds = {
  // artisan
  artisan_work_my_tools_need_for_monument : { sound:"artisan_e01.wav"},
  artisan_work_i_write_history_of_egypt : { sound:"artisan_e02.wav"},
  // barge
  barge_have_no_place_for_dock : { sound:"barge_e01.wav"},
  barge_docked_wait_for_dockpushers : { sound:"barge_e02.wav"},
  barge_city_not_trades : { sound:"barge_e03.wav"},
  barge_i_like_to_trage : { sound:"barge_e04.wav"},
  barge_amazing_trades : { sound:"barge_e05.wav"},
   // brick
  brick_bricklaying_time_at_monument : { sound:"brick_e01.wav"},
  brick_monument_will_be_strong : { sound:"brick_e02.wav"},
  // carpenter
  carpenter_work_my_tools_need_for_monument : { sound:"carpenter_e01.wav"},
  carpenter_this_monument_will_be_short : { sound:"carpenter_e02.wav"},
  // cartpusher
  cartpusher_no_one_available_to_unload : { sound:"cartpusher_e01.wav"},
  cartpusher_no_one_can_accept_these_goods : { sound:"cartpusher_e02.wav"},
  cartpusher_have_to_go_clear_across_city : { sound:"cartpusher_e03.wav"},
  // dancer
  dancer_festival_crowds : { sound:"dancer_e01.wav"},
  dancer_many_people_taken_ill : { sound:"dancer_g01.wav"},
  dancer_not_enough_food : { sound:"dancer_g02.wav"},
  dancer_nothing_defends_city : { sound:"dancer_g03.wav"},
  dancer_need_more_workers : { sound:"dancer_g04.wav"},
  dancer_gods_are_angry : { sound:"dancer_g05.wav"},
  dancer_reputation_is_low : { sound:"dancer_g06.wav"},
  dancer_unemployment_is_high : { sound:"dancer_g07.wav"},
  dancer_low_entertainment : { sound:"dancer_g08.wav"},
  dancer_city_is_ok : { sound:"dancer_g09.wav"},
  dancer_city_is_fantastic : { sound:"dancer_g10.wav"},
  // dentist
  dentist_concerned_about_plague : {sound:"dentist_g01.wav"},
  dentist_no_food_in_city : {sound:"dentist_g02.wav"},
  dentist_defenses_weak : {sound:"dentist_g03.wav"},
  dentist_need_more_workers : {sound:"dentist_g04.wav"},
  dentist_gods_are_angry : {sound:"dentist_g05.wav"},
  dentist_reputation_is_low : {sound:"dentist_g06.wav"},
  dentist_unemployment_is_high : {sound:"dentist_g07.wav"},
  dentist_low_entertainment : {sound:"dentist_g08.wav"},
  dentist_city_is_ok : {sound:"dentist_g09.wav"},
  dentist_city_is_the_best : {sound:"dentist_g10.wav"},
  // disease
  disease_oh_my_stomach_oh_my_head : {sound:"disease_e01.wav"},
  // dockpusher
  dockpusher_need_more_help : {sound:"dockpusher_e01.wav"},
  dockpusher_wait_until_space_opens_up : {sound:"dockpusher_e02.wav"},
  dockpusher_cant_haul_goods_much_farther : {sound:"dockpusher_e03.wav"},
  // doctor
  doctor_plague_could_strike_us_dead : {sound:"doctor_e01.WAV"},
  doctor_concerned_about_plague : {sound:"doctor_g01.WAV"},
  doctor_no_food_in_city : {sound:"doctor_g02.WAV"},
  doctor_defenses_weak : {sound:"doctor_g03.WAV"},
  doctor_need_more_workers : {sound:"doctor_g04.WAV"},
  doctor_gods_are_angry : {sound:"doctor_g05.WAV"},
  doctor_reputation_is_low : {sound:"doctor_g06.WAV"},
  doctor_unemployment_is_high : {sound:"doctor_g07.WAV"},
  doctor_low_entertainment : {sound:"doctor_g08.WAV"},
  doctor_city_is_ok : {sound:"doctor_g09.WAV"},
  doctor_city_is_the_best : {sound:"doctor_g10.WAV"},
  // embalmer
  embalmer_health_worsening : {sound:"embalmer_e01.WAV"},
  embalmer_concerned_about_plague : {sound:"embalmer_g01.WAV"},
  embalmer_no_food_in_city : {sound:"embalmer_g02.WAV"},
  embalmer_defenses_weak : {sound:"embalmer_g03.WAV"},
  embalmer_need_more_workers : {sound:"embalmer_g04.WAV"},
  embalmer_gods_are_angry : {sound:"embalmer_g05.WAV"},
  embalmer_reputation_is_low : {sound:"embalmer_g06.WAV"},
  embalmer_unemployment_is_high : {sound:"embalmer_g07.WAV"},
  embalmer_low_entertainment : {sound:"embalmer_g08.WAV"},
  embalmer_city_is_ok : {sound:"embalmer_g09.WAV"},
  embalmer_city_is_the_best : {sound:"embalmer_g10.WAV"},
  // emigrant
  emigrant_cant_find_a_job_here : {sound:"emigrant_e01.wav"},
  emigrant_not_enough_food : {sound:"emigrant_e02.wav"},
  emigrant_taxes_are_too_high : {sound:"emigrant_e03.wav"},
  emigrant_cant_live_on_what_pay_here : {sound:"emigrant_e04.wav"},
  emigrant_not_enough_housing : {sound:"emigrant_e05.wav"},
  // architect
  engineer_so_many_places_poor_condition : {sound:"engineer_e01.wav"},
  engineer_great_condition_of_city : {sound:"engineer_e02.wav"},
  engineer_concerned_about_plague : {sound:"engineer_g01.wav"},
  engineer_no_food_in_city : {sound:"engineer_g02.wav"},
  engineer_defenses_weak : {sound:"engineer_g03.wav"},
  engineer_need_more_workers : {sound:"engineer_g04.wav"},
  engineer_gods_are_angry : {sound:"engineer_g05.wav"},
  engineer_reputation_is_low : {sound:"engineer_g06.wav"},
  engineer_unemployment_is_high : {sound:"engineer_g07.wav"},
  engineer_low_entertainment : {sound:"engineer_g08.wav"},
  engineer_city_is_ok : {sound:"engineer_g09.wav"},
  engineer_city_is_the_best : {sound:"engineer_g10.wav"},
  // fireman
  fireman_busy_dousing_fire : {sound:"fireman_e01.wav"},
  fireman_whole_city_could_burn_down : {sound:"fireman_e02.wav"},
  fireman_oh_thats_hot : {sound:"fireman_e03.wav"},
  fireman_concerned_about_plague : {sound:"fireman_g01.wav"},
  fireman_no_food_in_city : {sound:"fireman_g02.wav"},
  fireman_defenses_weak : {sound:"fireman_g03.wav"},
  fireman_need_more_workers : {sound:"fireman_g04.wav"},
  fireman_gods_are_angry : {sound:"fireman_g05.wav"},
  fireman_reputation_is_low : {sound:"fireman_g06.wav"},
  fireman_unemployment_is_high : {sound:"fireman_g07.wav"},
  fireman_low_entertainment : {sound:"fireman_g08.wav"},
  fireman_city_is_ok : {sound:"fireman_g09.wav"},
  fireman_city_is_the_best : {sound:"fireman_g10.wav"},
  // fishing
  fishing_sound1 : {sound:"fishing_e01.wav"},
  fishing_sound2 : {sound:"fishing_e02.wav"},
  fishing_sound3 : {sound:"fishing_e03.wav"},
  // governor
  governor_city_left_much_nobles : {sound:"governor_e01.WAV"},
  governor_festival_was_near : {sound:"governor_e02.wav"},
  // guard
  guard_no_enemies_sighted : {sound:"guard_e01.wav"},
  guard_ready_approaching_enemy : {sound:"guard_e02.wav"},
  guard_no_trouble_defeating_army : {sound:"guard_e03.wav"},
  guard_enemy_is_fierce : {sound:"guard_e04.wav"},
  // hunt_ant
  hunt_ant_antelopes_no_match_for_us : {sound:"hunt_ant_e01.wav"},
  hunt_ant_steaks_for_everyone_tonight : {sound:"hunt_ant_e02.wav"},
  // hunt_bird
  hunt_bird_birds_are_wily : {sound:"hunt_bird_e01.wav"},
  hunt_bird_birds_ready_for_roasting : {sound:"hunt_bird_e02.wav"},
  // hunt_ostrich
  hunt_ostrich_heads_in_the_sand : {sound:"hunt_ostrich_e01.wav"},
  hunt_ostrich_those_are_big_drumsticks : {sound:"hunt_ostrich_e02.wav"},

  // juggler
  juggler_love_working_festival : {sound:"juggler_e01.wav"},
  juggler_never_seen_so_many_sick : {sound:"juggler_g01.wav"},
  juggler_no_food_in_city : {sound:"juggler_g02.wav"},
  juggler_little_is_defending_city : {sound:"juggler_g03.wav"},
  juggler_job_vacancies_everywhere : {sound:"juggler_g04.wav"},
  juggler_gods_think_weve_forgotten_them : {sound:"juggler_g05.wav"},
  juggler_reputation_is_low : {sound:"juggler_g06.wav"},
  juggler_high_unemployment : {sound:"juggler_g07.wav"},
  juggler_low_entertainment : {sound:"juggler_g08.wav"},
  juggler_city_is_ok : {sound:"juggler_g09.wav"},
  juggler_city_is_amazing : {sound:"juggler_g010.wav"},
  // Labor
  Labor_lot_of_people_need_jobs : { sound:"Labor_e01.wav"},
  Labor_cant_find_any_workers : { sound:"Labor_e02.wav"},
  Labor_people_are_sick : { sound:"Labor_g01.wav"},
  Labor_no_food_in_city : { sound:"Labor_g02.wav"},
  Labor_defenses_are_weak : { sound:"Labor_g03.wav"},
  Labor_without_workers_job_impossible : { sound:"Labor_g04.wav"},
  Labor_gods_are_angry : { sound:"Labor_g05.wav"},
  Labor_reputation_is_low : { sound:"Labor_g06.wav"},
  Labor_high_unemployment : { sound:"Labor_g07.wav"},
  Labor_low_entertainment : { sound:"Labor_g08.wav"},
  Labor_city_is_ok : { sound:"Labor_g09.wav"},
  Labor_city_is_amazing : { sound:"Labor_g10.wav"},
 // library
  library_read_about_festivals : { sound: "library_e01.wav"},
  library_people_are_sick : { sound: "library_g01.wav"},
  library_no_food_in_city : { sound: "library_g02.wav"},
  library_defenses_are_weak : { sound: "library_g03.wav"},
  library_need_more_workers : { sound: "library_g04.wav"},
  library_gods_are_angry : { sound: "library_g05.wav"},
  library_reputation_is_low : { sound: "library_g06.wav"},
  library_high_unemployment : { sound: "library_g07.wav"},
  library_low_entertainment : { sound: "library_g08.wav"},
  library_city_is_ok : { sound: "library_g09.wav"},
  library_city_is_amazing : { sound: "library_g10.wav"},
  // magistrate
  magistrate_hope_ill_earn_funeral : {sound: "magistrate_e02.wav"},
  magistrate_no_crime_here : {sound: "magistrate_e03.wav"},
  magistrate_only_petty_cases : {sound: "magistrate_e04.wav"},
  magistrate_streets_are_unsafe : {sound: "magistrate_e05.wav"},
  magistrate_danger_of_plague : {sound: "magistrate_g01.wav"},
  magistrate_no_food_in_city : {sound: "magistrate_g02.wav"},
  magistrate_defenses_are_weak : {sound: "magistrate_g03.wav"},
  magistrate_need_more_workers : {sound: "magistrate_g04.wav"},
  magistrate_gods_are_angry : {sound: "magistrate_g05.wav"},
  magistrate_reputation_is_low : {sound: "magistrate_g06.wav"},
  magistrate_high_unemployment : {sound: "magistrate_g07.wav"},
  magistrate_low_entertainment : {sound: "magistrate_g08.wav"},
  magistrate_city_is_ok : {sound: "magistrate_g09.wav"},
  magistrate_city_is_amazing : {sound: "magistrate_g10.wav"},
  // marketboy
  marketboy_these_baskets_are_too_heavy : {sound: "marketboy_e01.wav"},
  marketboy_bossy_lady_makes_me_carry_goods : {sound: "marketboy_e02.wav"},
  marketboy_one_day_ill_run_the_bazaar : {sound: "marketboy_e03.wav"},
  // mkt_buyer
  mkt_buyer_going_to_get_goods : {sound: "mkt_buyer_e01.wav"},
  mkt_buyer_taking_goods_to_bazaar : {sound: "mkt_buyer_e02.wav"},
  mkt_buyer_danger_of_plague : {sound: "mkt_buyer_g01.wav"},
  mkt_buyer_no_food_in_city : {sound: "mkt_buyer_g02.wav"},
  mkt_buyer_defenses_are_weak : {sound: "mkt_buyer_g03.wav"},
  mkt_buyer_need_more_workers : {sound: "mkt_buyer_g04.wav"},
  mkt_buyer_gods_are_angry : {sound: "mkt_buyer_g05.wav"},
  mkt_buyer_reputation_is_low : {sound: "mkt_buyer_g06.wav"},
  mkt_buyer_high_unemployment : {sound: "mkt_buyer_g07.wav"},
  mkt_buyer_low_entertainment : {sound: "mkt_buyer_g08.wav"},
  mkt_buyer_city_is_ok : {sound: "mkt_buyer_g09.wav"},
  mkt_buyer_city_is_amazing : {sound: "mkt_buyer_g10.wav"},
  // mkt_seller
  goods_are_finished : {sound: "mkt_seller_e01.wav"},
  we_are_selling_goods : {sound: "mkt_seller_e02.wav"},
  // musician
  musician_danger_of_plague : {sound: "musician_g01.wav"},
  musician_no_food_in_city : {sound: "musician_g02.wav"},
  musician_defenses_are_weak : {sound: "musician_g03.wav"},
  musician_need_more_workers : {sound: "musician_g04.wav"},
  musician_gods_are_angry : {sound: "musician_g05.wav"},
  musician_reputation_is_low : {sound: "musician_g06.wav"},
  musician_high_unemployment : {sound: "musician_g07.wav"},
  musician_low_entertainment : {sound: "musician_g08.wav"},
  musician_city_is_ok : {sound: "musician_g09.wav"},
  musician_city_is_amazing : {sound: "musician_g10.wav"},
 // pharaoh
  pharaoh_how_impertinent : {sound: "pharaoh_e01.wav"},
 // policeman
  policeman_low_crime_level : {sound: "police_e01.WAV"},
  policeman_usual_crime_level : {sound: "police_e02.WAV"},
  policeman_very_low_crime_level : {sound: "police_e03.WAV"},
  policeman_iam_too_busy_that_talk : {sound: "police_e04.WAV"},
  policeman_i_hope_my_work_is_need : {sound: "police_e05.WAV"},
  policeman_city_not_safety : {sound: "police_e06.WAV"},
  policeman_need_workers : {sound: "police_e07.WAV"},
  policeman_enemies_are_coming : {sound: "police_e08.WAV"},
  policeman_desease_can_start_at_any_moment : {sound: "police_g01.WAV"},
  policeman_no_food_in_city : {sound: "police_g02.WAV"},
  policeman_no_army : {sound: "police_g03.WAV"},
  policeman_need_more_workers : {sound: "police_g04.WAV"},
  policeman_gods_are_angry : {sound: "police_g05.WAV"},
  policeman_no_army_2 : {sound: "police_g06.wav"},
  policeman_much_unemployments : {sound: "police_g07.WAV"},
  policeman_low_entertainment : {sound: "police_g08.WAV"},
  policeman_city_is_good : {sound: "police_g09.WAV"},
  policeman_city_is_amazing : {sound: "police_g10.WAV"},
  // priest_bast
  priest_bast_festival : { sound: "priest_bast_e01.wav"},
  priest_bast_people_could_turn_to_crime : { sound: "priest_bast_e02.wav"},
  priest_bast_so_little_diversion : { sound: "priest_bast_e03.wav"},
  priest_bast_power_to_heal_the_sick : { sound: "priest_bast_e04.wav"},
  priest_bast_danger_of_plague : { sound: "priest_bast_g01.wav"},
  priest_bast_no_food_in_city : { sound: "priest_bast_g02.wav"},
  priest_bast_defenses_are_weak : { sound: "priest_bast_g03.wav"},
  priest_bast_need_more_workers : { sound: "priest_bast_g04.wav"},
  priest_bast_gods_are_angry : { sound: "priest_bast_g05.wav"},
  priest_bast_reputation_is_low : { sound: "priest_bast_g06.wav"},
  priest_bast_high_unemployment : { sound: "priest_bast_g07.wav"},
  priest_bast_low_entertainment : { sound: "priest_bast_g08.wav"},
  priest_bast_city_is_ok : { sound: "priest_bast_g09.wav"},
  priest_bast_city_is_amazing : { sound: "priest_bast_g10.wav"},
  // priest_osiris
  priest_osiris_festival : {sound: "priest_osiris_e01.wav"},
  priest_osiris_punish_with_low_flood : {sound: "priest_osiris_e02.wav"},
  priest_osiris_danger_of_plague : {sound: "priest_osiris_g01.wav"},
  priest_osiris_no_food_in_city : {sound: "priest_osiris_g02.wav"},
  priest_osiris_defenses_are_weak : {sound: "priest_osiris_g03.wav"},
  priest_osiris_need_more_workers : {sound: "priest_osiris_g04.wav"},
  priest_osiris_gods_are_angry : {sound: "priest_osiris_g05.wav"},
  priest_osiris_reputation_is_low : {sound: "priest_osiris_g06.wav"},
  priest_osiris_high_unemployment : {sound: "priest_osiris_g07.wav"},
  priest_osiris_low_entertainment : {sound: "priest_osiris_g08.wav"},
  priest_osiris_city_is_ok : {sound: "priest_osiris_g09.wav"},
  priest_osiris_city_is_amazing : {sound: "priest_osiris_g10.wav"},
  // priest_ptah
  priest_ptah_festival : {sound: "priest_ptah_e01.wav"},
  priest_ptah_industry_needs_workers : {sound: "priest_ptah_e02.wav"},
  priest_ptah_danger_of_plague : {sound: "priest_ptah_g01.wav"},
  priest_ptah_no_food_in_city : {sound: "priest_ptah_g02.wav"},
  priest_ptah_defenses_are_weak : {sound: "priest_ptah_g03.wav"},
  priest_ptah_need_more_workers : {sound: "priest_ptah_g04.wav"},
  priest_ptah_gods_are_angry : {sound: "priest_ptah_g05.wav"},
  priest_ptah_reputation_is_low : {sound: "priest_ptah_g06.wav"},
  priest_ptah_high_unemployment : {sound: "priest_ptah_g07.wav"},
  priest_ptah_low_entertainment : {sound: "priest_ptah_g08.wav"},
  priest_ptah_city_is_amazing : {sound: "priest_ptah_g10.wav"},
  // priest_ra
  priest_ra_festival : { sound: "priest_ra_e01.wav"},
  priest_ra_city_is_an_embarrasment : { sound: "priest_ra_e02.wav"},
  priest_ra_danger_of_plague : { sound: "priest_ra_g01.wav"},
  priest_ra_no_food_in_city : { sound: "priest_ra_g02.wav"},
  priest_ra_defenses_are_weak : { sound: "priest_ra_g03.wav"},
  priest_ra_need_more_workers : { sound: "priest_ra_g04.wav"},
  priest_ra_gods_are_angry : { sound: "priest_ra_g05.wav"},
  priest_ra_reputation_is_low : { sound: "priest_ra_g06.wav"},
  priest_ra_high_unemployment : { sound: "priest_ra_g07.wav"},
  priest_ra_low_entertainment : { sound: "priest_ra_g08.wav"},
  priest_ra_city_is_ok : { sound: "priest_ra_g09.wav"},
  priest_ra_city_is_amazing : { sound: "priest_ra_g10.wav"},
  // priest_seth
  priest_seth_festival : {sound: "priest_seth_e01.wav"},
  priest_seth_enemies_approaching : {sound: "priest_seth_e02.wav"},
  priest_seth_danger_of_plague : {sound: "priest_seth_g01.wav"},
  priest_seth_no_food_in_city : {sound: "priest_seth_g02.wav"},
  priest_seth_defenses_are_weak : {sound: "priest_seth_g03.wav"},
  priest_seth_need_more_workers : {sound: "priest_seth_g04.wav"},
  priest_seth_gods_are_angry : {sound: "priest_seth_g05.wav"},
  priest_seth_reputation_is_low : {sound: "priest_seth_g06.wav"},
  priest_seth_high_unemployment : {sound: "priest_seth_g07.wav"},
  priest_seth_low_entertainment : {sound: "priest_seth_g08.wav"},
  priest_seth_city_is_ok : {sound: "priest_seth_g09.wav"},
  priest_seth_city_is_amazing : {sound: "priest_seth_g10.wav"},
 // reed
  reed_to_the_marsh_i_march : { sound: "REED_E01.WAV"},
  reed_will_make_some_fine_papyrus : { sound: "REED_E02.WAV"},
  // robber
  robber_gold_should_be_for_living : { sound: "robber_e01.wav"},
  robber_just_think_of_the_fortune : { sound: "robber_e02.wav"},
  // scribe
  scribe_these_festivals : { sound: "scribe_e01.wav"},
  scribe_plague_could_break_out : { sound: "scribe_g01.wav"},
  scribe_no_food_in_city : { sound: "scribe_g02.wav"},
  scribe_defenses_are_weak : { sound: "scribe_g03.wav"},
  scribe_need_more_workers : { sound: "scribe_g04.wav"},
  scribe_gods_are_angry : { sound: "scribe_g05.wav"},
  scribe_reputation_is_low : { sound: "scribe_g06.wav"},
  scribe_high_unemployment : { sound: "scribe_g07.wav"},
  scribe_low_entertainment : { sound: "scribe_g08.wav"},
  scribe_city_is_ok : { sound: "scribe_g09.wav"},
  scribe_city_is_amazing : { sound: "scribe_g10.wav"},
  // senet
  senet_get_your_beer_here : { sound: "senet_e01.wav"},
  senet_risk_of_plague : { sound: "senet_g01.wav"},
  senet_no_food_in_city : { sound: "senet_g02.wav"},
  senet_defenses_are_weak : { sound: "senet_g03.wav"},
  senet_need_more_workers : { sound: "senet_g04.wav"},
  senet_gods_are_angry : { sound: "senet_g05.wav"},
  senet_reputation_is_low : { sound: "senet_g06.wav"},
  senet_high_unemployment : { sound: "senet_g07.wav"},
  senet_low_entertainment : { sound: "senet_g08.wav"},
  senet_city_is_ok : { sound: "senet_g09.wav"},
  senet_city_is_amazing : { sound: "senet_g10.wav"},
  // stone
  stone_going_to_monument : { sound: "stone_e01.wav"},
  stone_my_work_will_endure : { sound: "stone_e02.wav"},
  // taxman
  taxman_need_more_tax_collectors : { sound: "taxman_e01.wav"},
  taxman_the_nicer_the_houses : { sound: "taxman_e02.wav"},
  taxman_hate_rundown_houses : { sound: "taxman_e03.wav"},
  taxman_danger_of_plague : { sound: "taxman_g01.wav"},
  taxman_no_food_in_city : { sound: "taxman_g02.wav"},
  taxman_defenses_are_weak : { sound: "taxman_g03.wav"},
  taxman_need_more_workers : { sound: "taxman_g04.wav"},
  taxman_gods_are_angry : { sound: "taxman_g05.wav"},
  taxman_reputation_is_low : { sound: "taxman_g06.wav"},
  taxman_high_unemployment : { sound: "taxman_g07.wav"},
  taxman_low_entertainment : { sound: "taxman_g08.wav"},
  taxman_city_is_ok : { sound: "taxman_g09.wav"},
  taxman_city_is_amazing : { sound: "taxman_g10.wav"},
 // teacher
  teacher_festival_info : { sound: "teacher_e01.wav"},
  teacher_desease_can_start_at_any_moment : { sound: "teacher_g01.wav"},
  teacher_no_food_in_city : { sound: "teacher_g02.wav"},
  teacher_city_not_safety : { sound: "teacher_g03.wav"},
  teacher_need_workers : { sound: "teacher_g04.wav"},
  teacher_gods_are_angry : { sound: "teacher_g05.wav"},
  teacher_low_rating : { sound: "teacher_g06.wav"},
  teacher_much_unemployments : { sound: "teacher_g07.wav"},
  teacher_city_is_good : { sound: "teacher_g08.wav"},
  teacher_city_much_better : { sound: "teacher_g09.wav"},
  teacher_city_is_amazing : { sound: "teacher_g10.wav"},
  // thief
  thief_maybe_stealing_will_get_attention : { sound: "thief_e01.wav"},
  thief_i_take_what_i_want : { sound: "thief_e02.wav"},
  thief_more_profitable_than_other_jobs : { sound: "thief_e03.wav"},
  thief_take_take_take : { sound: "thief_e04.wav"},
  // transport
  transport_must_protect_our_ship : { sound: "transport_e01.wav"},
  transport_enemy_is_here : { sound: "transport_e02.wav"},
  transport_were_prepared : { sound: "transport_e03.wav"},
  transport_ready_if_need_arises : { sound: "transport_e04.wav"},
  // vagrant
  vagrant_kicked_out_of_my_home : { sound: "vagrant_e01.wav"},
  vagrant_cant_find_a_place_to_live : { sound: "vagrant_e02.wav"},
  // warship
  warship_well_fight_to_the_death : { sound: "warship_e01.wav"},
  warship_enemy_is_too_much_for_us : { sound: "warship_e02.wav"},
  warship_enemies_coming_this_way : { sound: "warship_e03.wav"},
  warship_ready_to_attack_invaders : { sound: "warship_e04.wav"},
  warship_ready_if_foes_come : { sound: "warship_e05.wav"},
  // water
  water_danger_of_plague : { sound: "water_g01.wav"},
  water_no_food_in_city : { sound: "water_g02.wav"},
  water_defenses_are_weak : { sound: "water_g03.wav"},
  water_need_more_workers : { sound: "water_g04.wav"},
  water_gods_are_angry : { sound: "water_g05.wav"},
  water_reputation_is_low : { sound: "water_g06.wav"},
  water_high_unemployment : { sound: "water_g07.wav"},
  water_low_entertainment : { sound: "water_g08.wav"},
  water_city_is_ok : { sound: "water_g09.wav"},
  water_city_is_amazing : { sound: "water_g10.wav"},
  // woodcutter
  woodcutter_hard_days_logging : { sound: "woodcutter_e01.wav"},
  woodcutter_timber_put_to_good_use : { sound: "woodcutter_e02.wav"},
  // worker
  worker_im_ready_to_work : { sound: "worker_e02.wav"},
  worker_fields_under_water : { sound: "worker_e03.wav"},
  worker_danger_of_plague : { sound: "worker_g01.wav"},
  worker_no_food_in_city : { sound: "worker_g02.wav"},
  worker_defenses_are_weak : { sound: "worker_g03.wav"},
  worker_need_more_workers : { sound: "worker_g04.wav"},
  worker_gods_are_angry : { sound: "worker_g05.wav"},
  worker_reputation_is_low : { sound: "worker_g06.wav"},
  worker_high_unemployment : { sound: "worker_g07.wav"},
  worker_low_entertainment : { sound: "worker_g08.wav"},
  worker_city_is_ok : { sound: "worker_g09.wav"},
  worker_city_is_amazing : { sound: "worker_g10.wav"},
  // zookeeper
  zookeeper_danger_of_plague : { sound: "zookeeper_e01.wav"},
  zookeeper_no_food_in_city : { sound: "zookeeper_e02.wav"},
  zookeeper_defenses_are_weak : { sound: "zookeeper_e03.wav"},
  zookeeper_need_more_workers : { sound: "zookeeper_e04.wav"},
  zookeeper_gods_are_angry : { sound: "zookeeper_e05.wav"},
  zookeeper_reputation_is_low : { sound: "zookeeper_e06.wav"},
  zookeeper_high_unemployment : { sound: "zookeeper_e07.wav"},
  zookeeper_low_entertainment : { sound: "zookeeper_e08.wav"},
  zookeeper_city_is_ok : { sound: "zookeeper_e09.wav"},
  zookeeper_city_is_amazing : { sound: "zookeeper_e10.wav"}
}
