log_info("akhenaten: walker sounds started")

walker_sounds = {
  // artisan
  artisan_work_my_tools_need_for_monument : { sound:"artisan_e01.wav"},
  artisan_work_i_write_history_of_egypt : { sound:"artisan_e02.wav"},
  // disease
  disease_oh_my_stomach_oh_my_head : {sound:"disease_e01.wav"},
  // dockpusher
  dockpusher_need_more_help : {sound:"dockpusher_e01.wav"},
  dockpusher_wait_until_space_opens_up : {sound:"dockpusher_e02.wav"},
  dockpusher_cant_haul_goods_much_farther : {sound:"dockpusher_e03.wav"},

  // guard
  guard_no_enemies_sighted : {sound:"guard_e01.wav"},
  guard_ready_approaching_enemy : {sound:"guard_e02.wav"},
  guard_no_trouble_defeating_army : {sound:"guard_e03.wav"},
  guard_enemy_is_fierce : {sound:"guard_e04.wav"},
  // hunt_ant
  hunt_ant_antelopes_no_match_for_us : {sound:"hunt_ant_e01.wav"},
  hunt_ant_steaks_for_everyone_tonight : {sound:"hunt_ant_e02.wav"},
  // hunt_bird
  hunt_bird_birds_are_wily : {sound:"hunt_bird_e01.wav"},
  hunt_bird_birds_ready_for_roasting : {sound:"hunt_bird_e02.wav"},

  // mkt_seller
  goods_are_finished : {sound: "mkt_seller_e01.wav"},
  we_are_selling_goods : {sound: "mkt_seller_e02.wav"},
  // pharaoh
  pharaoh_how_impertinent : {sound: "pharaoh_e01.wav"},
  // priest_bast
  priest_bast_festival : { sound: "priest_bast_e01.wav"},
  priest_bast_people_could_turn_to_crime : { sound: "priest_bast_e02.wav"},
  priest_bast_so_little_diversion : { sound: "priest_bast_e03.wav"},
  priest_bast_power_to_heal_the_sick : { sound: "priest_bast_e04.wav"},
  priest_bast_danger_of_plague : { sound: "priest_bast_g01.wav"},
  priest_bast_no_food_in_city : { sound: "priest_bast_g02.wav"},
  priest_bast_defenses_are_weak : { sound: "priest_bast_g03.wav"},
  priest_bast_need_more_workers : { sound: "priest_bast_g04.wav"},
  priest_bast_gods_are_angry : { sound: "priest_bast_g05.wav"},
  priest_bast_reputation_is_low : { sound: "priest_bast_g06.wav"},
  priest_bast_high_unemployment : { sound: "priest_bast_g07.wav"},
  priest_bast_low_entertainment : { sound: "priest_bast_g08.wav"},
  priest_bast_city_is_ok : { sound: "priest_bast_g09.wav"},
  priest_bast_city_is_amazing : { sound: "priest_bast_g10.wav"},
  // priest_osiris
  priest_osiris_festival : {sound: "priest_osiris_e01.wav"},
  priest_osiris_punish_with_low_flood : {sound: "priest_osiris_e02.wav"},
  priest_osiris_danger_of_plague : {sound: "priest_osiris_g01.wav"},
  priest_osiris_no_food_in_city : {sound: "priest_osiris_g02.wav"},
  priest_osiris_defenses_are_weak : {sound: "priest_osiris_g03.wav"},
  priest_osiris_need_more_workers : {sound: "priest_osiris_g04.wav"},
  priest_osiris_gods_are_angry : {sound: "priest_osiris_g05.wav"},
  priest_osiris_reputation_is_low : {sound: "priest_osiris_g06.wav"},
  priest_osiris_high_unemployment : {sound: "priest_osiris_g07.wav"},
  priest_osiris_low_entertainment : {sound: "priest_osiris_g08.wav"},
  priest_osiris_city_is_ok : {sound: "priest_osiris_g09.wav"},
  priest_osiris_city_is_amazing : {sound: "priest_osiris_g10.wav"},
  // priest_ptah
  priest_ptah_festival : {sound: "priest_ptah_e01.wav"},
  priest_ptah_industry_needs_workers : {sound: "priest_ptah_e02.wav"},
  priest_ptah_danger_of_plague : {sound: "priest_ptah_g01.wav"},
  priest_ptah_no_food_in_city : {sound: "priest_ptah_g02.wav"},
  priest_ptah_defenses_are_weak : {sound: "priest_ptah_g03.wav"},
  priest_ptah_need_more_workers : {sound: "priest_ptah_g04.wav"},
  priest_ptah_gods_are_angry : {sound: "priest_ptah_g05.wav"},
  priest_ptah_reputation_is_low : {sound: "priest_ptah_g06.wav"},
  priest_ptah_high_unemployment : {sound: "priest_ptah_g07.wav"},
  priest_ptah_low_entertainment : {sound: "priest_ptah_g08.wav"},
  priest_ptah_city_is_amazing : {sound: "priest_ptah_g10.wav"},
  // priest_ra
  priest_ra_festival : { sound: "priest_ra_e01.wav"},
  priest_ra_city_is_an_embarrasment : { sound: "priest_ra_e02.wav"},
  priest_ra_danger_of_plague : { sound: "priest_ra_g01.wav"},
  priest_ra_no_food_in_city : { sound: "priest_ra_g02.wav"},
  priest_ra_defenses_are_weak : { sound: "priest_ra_g03.wav"},
  priest_ra_need_more_workers : { sound: "priest_ra_g04.wav"},
  priest_ra_gods_are_angry : { sound: "priest_ra_g05.wav"},
  priest_ra_reputation_is_low : { sound: "priest_ra_g06.wav"},
  priest_ra_high_unemployment : { sound: "priest_ra_g07.wav"},
  priest_ra_low_entertainment : { sound: "priest_ra_g08.wav"},
  priest_ra_city_is_ok : { sound: "priest_ra_g09.wav"},
  priest_ra_city_is_amazing : { sound: "priest_ra_g10.wav"},
  // priest_seth
  priest_seth_festival : {sound: "priest_seth_e01.wav"},
  priest_seth_enemies_approaching : {sound: "priest_seth_e02.wav"},
  priest_seth_danger_of_plague : {sound: "priest_seth_g01.wav"},
  priest_seth_no_food_in_city : {sound: "priest_seth_g02.wav"},
  priest_seth_defenses_are_weak : {sound: "priest_seth_g03.wav"},
  priest_seth_need_more_workers : {sound: "priest_seth_g04.wav"},
  priest_seth_gods_are_angry : {sound: "priest_seth_g05.wav"},
  priest_seth_reputation_is_low : {sound: "priest_seth_g06.wav"},
  priest_seth_high_unemployment : {sound: "priest_seth_g07.wav"},
  priest_seth_low_entertainment : {sound: "priest_seth_g08.wav"},
  priest_seth_city_is_ok : {sound: "priest_seth_g09.wav"},
  priest_seth_city_is_amazing : {sound: "priest_seth_g10.wav"},
 // reed
  reed_to_the_marsh_i_march : { sound: "REED_E01.WAV"},
  reed_will_make_some_fine_papyrus : { sound: "REED_E02.WAV"},
  // robber
  robber_gold_should_be_for_living : { sound: "robber_e01.wav"},
  robber_just_think_of_the_fortune : { sound: "robber_e02.wav"},
  // scribe
  scribe_these_festivals : { sound: "scribe_e01.wav"},
  scribe_plague_could_break_out : { sound: "scribe_g01.wav"},
  scribe_no_food_in_city : { sound: "scribe_g02.wav"},
  scribe_defenses_are_weak : { sound: "scribe_g03.wav"},
  scribe_need_more_workers : { sound: "scribe_g04.wav"},
  scribe_gods_are_angry : { sound: "scribe_g05.wav"},
  scribe_reputation_is_low : { sound: "scribe_g06.wav"},
  scribe_high_unemployment : { sound: "scribe_g07.wav"},
  scribe_low_entertainment : { sound: "scribe_g08.wav"},
  scribe_city_is_ok : { sound: "scribe_g09.wav"},
  scribe_city_is_amazing : { sound: "scribe_g10.wav"},
  // senet
  senet_get_your_beer_here : { sound: "senet_e01.wav"},
  senet_risk_of_plague : { sound: "senet_g01.wav"},
  senet_no_food_in_city : { sound: "senet_g02.wav"},
  senet_defenses_are_weak : { sound: "senet_g03.wav"},
  senet_need_more_workers : { sound: "senet_g04.wav"},
  senet_gods_are_angry : { sound: "senet_g05.wav"},
  senet_reputation_is_low : { sound: "senet_g06.wav"},
  senet_high_unemployment : { sound: "senet_g07.wav"},
  senet_low_entertainment : { sound: "senet_g08.wav"},
  senet_city_is_ok : { sound: "senet_g09.wav"},
  senet_city_is_amazing : { sound: "senet_g10.wav"},
  // stone
  stone_going_to_monument : { sound: "stone_e01.wav"},
  stone_my_work_will_endure : { sound: "stone_e02.wav"},
  // taxman
  taxman_need_more_tax_collectors : { sound: "taxman_e01.wav"},
  taxman_the_nicer_the_houses : { sound: "taxman_e02.wav"},
  taxman_hate_rundown_houses : { sound: "taxman_e03.wav"},
  taxman_danger_of_plague : { sound: "taxman_g01.wav"},
  taxman_no_food_in_city : { sound: "taxman_g02.wav"},
  taxman_defenses_are_weak : { sound: "taxman_g03.wav"},
  taxman_need_more_workers : { sound: "taxman_g04.wav"},
  taxman_gods_are_angry : { sound: "taxman_g05.wav"},
  taxman_reputation_is_low : { sound: "taxman_g06.wav"},
  taxman_high_unemployment : { sound: "taxman_g07.wav"},
  taxman_low_entertainment : { sound: "taxman_g08.wav"},
  taxman_city_is_ok : { sound: "taxman_g09.wav"},
  taxman_city_is_amazing : { sound: "taxman_g10.wav"},
 // teacher
  teacher_festival_info : { sound: "teacher_e01.wav"},
  teacher_desease_can_start_at_any_moment : { sound: "teacher_g01.wav"},
  teacher_no_food_in_city : { sound: "teacher_g02.wav"},
  teacher_city_not_safety : { sound: "teacher_g03.wav"},
  teacher_need_workers : { sound: "teacher_g04.wav"},
  teacher_gods_are_angry : { sound: "teacher_g05.wav"},
  teacher_low_rating : { sound: "teacher_g06.wav"},
  teacher_much_unemployments : { sound: "teacher_g07.wav"},
  teacher_city_is_good : { sound: "teacher_g08.wav"},
  teacher_city_much_better : { sound: "teacher_g09.wav"},
  teacher_city_is_amazing : { sound: "teacher_g10.wav"},
  // thief
  thief_maybe_stealing_will_get_attention : { sound: "thief_e01.wav"},
  thief_i_take_what_i_want : { sound: "thief_e02.wav"},
  thief_more_profitable_than_other_jobs : { sound: "thief_e03.wav"},
  thief_take_take_take : { sound: "thief_e04.wav"},
  // transport
  transport_must_protect_our_ship : { sound: "transport_e01.wav"},
  transport_enemy_is_here : { sound: "transport_e02.wav"},
  transport_were_prepared : { sound: "transport_e03.wav"},
  transport_ready_if_need_arises : { sound: "transport_e04.wav"},
  // vagrant
  vagrant_kicked_out_of_my_home : { sound: "vagrant_e01.wav"},
  vagrant_cant_find_a_place_to_live : { sound: "vagrant_e02.wav"},
  // warship
  warship_well_fight_to_the_death : { sound: "warship_e01.wav"},
  warship_enemy_is_too_much_for_us : { sound: "warship_e02.wav"},
  warship_enemies_coming_this_way : { sound: "warship_e03.wav"},
  warship_ready_to_attack_invaders : { sound: "warship_e04.wav"},
  warship_ready_if_foes_come : { sound: "warship_e05.wav"},
  // water
  water_danger_of_plague : { sound: "water_g01.wav"},
  water_no_food_in_city : { sound: "water_g02.wav"},
  water_defenses_are_weak : { sound: "water_g03.wav"},
  water_need_more_workers : { sound: "water_g04.wav"},
  water_gods_are_angry : { sound: "water_g05.wav"},
  water_reputation_is_low : { sound: "water_g06.wav"},
  water_high_unemployment : { sound: "water_g07.wav"},
  water_low_entertainment : { sound: "water_g08.wav"},
  water_city_is_ok : { sound: "water_g09.wav"},
  water_city_is_amazing : { sound: "water_g10.wav"},
  // worker
  worker_im_ready_to_work : { sound: "worker_e02.wav"},
  worker_fields_under_water : { sound: "worker_e03.wav"},
  worker_danger_of_plague : { sound: "worker_g01.wav"},
  worker_no_food_in_city : { sound: "worker_g02.wav"},
  worker_defenses_are_weak : { sound: "worker_g03.wav"},
  worker_need_more_workers : { sound: "worker_g04.wav"},
  worker_gods_are_angry : { sound: "worker_g05.wav"},
  worker_reputation_is_low : { sound: "worker_g06.wav"},
  worker_high_unemployment : { sound: "worker_g07.wav"},
  worker_low_entertainment : { sound: "worker_g08.wav"},
  worker_city_is_ok : { sound: "worker_g09.wav"},
  worker_city_is_amazing : { sound: "worker_g10.wav"},
  // zookeeper
  zookeeper_danger_of_plague : { sound: "zookeeper_e01.wav"},
  zookeeper_no_food_in_city : { sound: "zookeeper_e02.wav"},
  zookeeper_defenses_are_weak : { sound: "zookeeper_e03.wav"},
  zookeeper_need_more_workers : { sound: "zookeeper_e04.wav"},
  zookeeper_gods_are_angry : { sound: "zookeeper_e05.wav"},
  zookeeper_reputation_is_low : { sound: "zookeeper_e06.wav"},
  zookeeper_high_unemployment : { sound: "zookeeper_e07.wav"},
  zookeeper_low_entertainment : { sound: "zookeeper_e08.wav"},
  zookeeper_city_is_ok : { sound: "zookeeper_e09.wav"},
  zookeeper_city_is_amazing : { sound: "zookeeper_e10.wav"}
}
