#pragma once

enum e_invasion_type {
    INVASION_TYPE_LOCAL_UPRISING = 1,
    INVASION_TYPE_ENEMY_ARMY = 2,
    INVASION_TYPE_KNGDOME = 3,
    INVASION_TYPE_DISTANT_BATTLE = 4,
};

enum e_eqrthquake_type { 
    EARTHQUAKE_NONE = 0,
    EARTHQUAKE_SMALL = 1,
    EARTHQUAKE_MEDIUM = 2,
    EARTHQUAKE_LARGE = 3
};
