name: Akhenaten Build Mac x86_64

on:
  workflow_call:

jobs:
  build:
    name: run on mac x86_64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: update-workspace
      run: |
        export CXXFLAGS=-stdlib=libc++
        cmake --preset macos-clang-relwithdebinfo-make-x86_64 \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
          -DOPTION_SYSTEM_LIBPNG=OFF \
          -DOPTION_BUILD_LIBPNG=ON \
          -DCMAKE_INSTALL_PREFIX="$PWD/build/install"

    - name: build
      run: |
        cmake --build --preset macos-clang-relwithdebinfo-make-x86_64 -- -j$(sysctl -n hw.ncpu)

    - name: install-and-bundle
      run: |
        cmake --build --preset macos-clang-relwithdebinfo-make-x86_64 --target install/local
        mkdir macos_build
        cp -R ./build/install/akhenaten.app ./macos_build/akhenaten.app

    - uses: actions/upload-artifact@v6
      with:
        name: macos_x64_build
        path: macos_build
