name: Clang Format

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Clang Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: './src'
          extensions: 'h,cpp,c,hpp'
          clangFormatVersion: 15
